version: "3.4"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Root@123

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  andreiaferreiraclinicaapi:
    build: # Define que será usado um Dockerfile
      context: . # Diretório do build (geralmente onde está o Dockerfile)
      dockerfile: ./Dockerfile # Caminho para o Dockerfile (se não estiver no mesmo nível, ajuste o caminho)
    ports:
      - "5245:80"
    depends_on:
      - db