# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  andreiaferreiraclinicaapi:
    image: atilao450/andreia.ferreira.backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5245:80
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: Root@123

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
